name: Build a Docker image and Push it to ACR

on:
  workflow_dispatch:
#  push:
#    branches:
#      - dev

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
#      uses: actions/checkout@v1
#      with:
#        ref: main

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        path: .
        dockerfile: './src/Dockerfile.KubeAdmin'
        repository: 'whack-a-mole'
        tags: 'latest'
        push: true
